### ISSUE TITLE
[Feature Request] Ability to work with capture card sources and track mouse? (on a different machine)

### ISSUE THREAD

**Issue by JoqniX** [BlankSourceCode/obs-zoom-to-mouse#11]
hewwo! i've been using the the plugin! its satisfied alot! thank you for making it! it is really helping alot! 
i was wondering if it would be somehow possible to get the mouse coordinates from a different machine and make it work on capture card sources ? since i mainly use my game pc for my work streams and such, which needs this plugin alot. since there's alot of limitations if you're a dual pc user right? either i have obs running on game pc and send the feed via ndi or the obs preview window method etc are my only choice atm. ( since i'm trying to balance the resources load on game pc i usually not use obs )  but yea if it was somehow possible to do this without having obs running on game pc and make it send the mouse coords etc to stream pc's obs where the obs-zoom-to-mouse plugin reads it that would be really help alot! 

since there isn't much solutions to this use case! but i think its definately might be possible somehow? right? do give me your thoughts too! and if there's others so find this and if you're an dual pc user like me do share your thoughts on this as well! 

**the following is what i think would work** 
> so i was thinking like! some script or something which a user has to run on their another system ( for example - game pc) which tracks the mouse coords? and sends that info back to the stream pc's obs (where the plugin/script is installed!) 
> 
> or maybe what if the user just installs the script like normally? and let it act as a remote thingy? that would work but taht would require the user on game pc to have obs running? ig for those who dont wanna run obs? can have a external application/script which they needa launch or something? 
> 
> then a option in the zoom-to-follow script to connect to that script or some sort ( maybe you can do like a connect to a ip kinda? since most likely these machines would be connected over the locally via ethernet so ip might work ig? ) 
> 
> so that would mean if remote mouse follow is enabled? then original (current machine's mouse follow will be disabled?) maybe having an option for that would help alot ig!

but yea again do lmk if this could be possible! ofc since its a lua script, there would be limitations and stuff. but yea even if its not possible. if you have any ideas or know any other methods do lmk! 

again thank you for reading this! hope you have a good day ahead! ✨

**Comment by BlankSourceCode** [comment]
OBS lua doesn't have much support in the way of getting external data. So it would be tricky to request/receive the cursor position from a remote machine.

Off the top of my head, you might be able to do something with a [udp port](https://obsproject.com/forum/threads/using-udp-ports-in-obs-lua.157274/) in the script. You'd also need something running on the remote machine that sent the mouse position to that udp port, such as a C# application or similar. I have no idea if that would work, and if it did, I'm not sure how laggy such a communication would be.

It seems like a bit much to support out of the box, but maybe someone has a better idea on how it could work?

**Comment by BlankSourceCode** [comment]
@JoqniX I don't use a 2pc setup so I have a couple of questions on how this might work.

First this is what I think you are talking about:

* You have 2 machines:
   * OBS PC - machine with OBS installed
   * Game PC - machine without OBS installed
* You connect the Game PC to the OBS PC by plugging in an hdmi cable from Game PC into a capture card on OBS PC
* You add a new video capture source in OBS and point it at the capture card

Now your OBS is showing/recording content from the Game PC, and you want to zoom into something on the Game PC.

* You move the mouse on the Game PC to where you want to zoom
* You press a hotkey on the OBS PC(?) to toggle zoom

OBS zooms the video capture source into the position of the cursor on the Game PC.

I am assuming you normally control OBS stuff by interacting with the OBS PC and not the Game PC, so you would press the hotkey on the OBS PC to toggle the zoom. Is that true?

If you didn't mind also moving the mouse on the OBS PC, you can sort of get it to work with the current script today.

##

Here is how it could "work" today (if you don't mind using the mouse on the OBS PC):

* Setup your 2 machines as above, and add the video capture source on OBS
* In OBS, enable `Allow any zoom source` so that the video capture source is available in the dropdown
* In the `Zoom Source` dropdown, select your video capture source
* Enable `Set manual source position`
* Set the position and size settings to match the monitor that you are capturing on the Game PC
   * Let's say your Game PC is a single monitor using 1920x1080 which is also the same as your recording canvas size in OBS (if not you'd have to modify the settings below)
   * X = 0
   * Y = 0
   * Width = 1920
   * Height = 1080
   * ScaleX = 1
   * ScaleY = 1

Now when you press the hotkey, obs-zoom-to-mouse will zoom into the Game PC video capture source, but using the mouse coordinates from OBS PC. So if you move your mouse to 0,0 on the OBS PC, it will zoom into the top-left corner of the video capture source.

"But I can't tell where my zoom is going to go because I'm moving the mouse on the wrong PC" - Yes, this is true, so lets make it a bit easier:
* Add a new Scene to OBS
* In the new scene, add a new video capture (not existing) and point it to the capture card
* Right-click the new Scene in OBS and select `Windowed Projector (Scene)`
* Move and resize this window so that it sits at the same coordinates as the ones you set manually above

Now you can move the mouse on the OBS PC over the windowed projector and toggle the zoom hotkey. OBS will zoom into the original video capture using the coordinates on the mouse on the OBS PC, but because you have the game displayed in a window at that location you'll know where you are zooming into.

Is it a mess? yes. Does it probably require a lot of processing power on the OBS PC? also yes. Does it solve your scenario? eh.. maybe?

##

If you really want to move the mouse on the Game PC, here are my questions:

1. Did I get the setup in the first part correct? (Is that how your setup works with the 2 PCs?)
1. Do you need to be able to press the toggle zoom hotkey on the Game PC? (or is pressing the zoom hotkey on the OBS PC fine?)
1. Do you need this to work cross platform? (aka are you using only Windows machines, or is your game/obs machine actually running Mac and/or Linux?)
1. Is this a common way to record/stream (aka using 2 machines) and also wanting to zoom?

Sorry for all the text. If anyone else out there is interesting in such a feature, reply back and let me know.

**Comment by JoqniX** [comment]
ill try to share this issue around so others could find it and also suggest us some good methods to tackle this! i hope its okie >///<

**Comment by BlankSourceCode** [comment]
@JoqniX It seems like you use your dual machine setup in many different ways. Sometimes you have OBS open on both machines,  sometimes you don't, sometimes you use a capture card, sometimes you use NDI, sometimes you use a bunch of different software I've never heard of, sometimes you multi-stream, the list goes on.

I'm only one person, so I doubt I have the time to make something that works in all those different scenarios.

How about this, I tell you what I *can* do and you tell me if it would be useful or not?

Here is what I can make:

1. I update `obs-zoom-to-mouse.lua` so that it has a UDP socket server you can enable
2. I make a small application that sends the current mouse position to that socket server

This is how it would work:

1. Add the modified `obs-zoom-to-mouse.lua` on the OBS PC
2. Enable the socket server option
4. Add the small application to the Game PC
5. Run the small application and specify the OBS PC's ip address where it can send mouse positions to
6. Everything else is as normal:
   1. You select a zoom source in `obs-zoom-to-mouse.lua` on the OBS PC (I assume the capture or NDI source that is coming from the Game PC)
   2. You enable the `Set manual source position` option in `obs-zoom-to-mouse.lua` and set the X/Y/Width/Height to the position of the source on the other machine (since the script will have no way of knowing that)
   3. You press the toggle zoom hotkey on the OBS PC
   4. It will zoom into the selected zoom source
   5. Instead of using the local mouse position like it does today, it uses the mouse position from the Game PC
   6. As you move the mouse on your Game PC, the zoom on the OBS PC moves around

**Would that be useful?**

**Comment by BlankSourceCode** [comment]
@JoqniX - Here is a new repo that contains the small program that you need to run on the second PC:
[obs-zoom-to-mouse-remote](https://github.com/BlankSourceCode/obs-zoom-to-mouse-remote)

You'll also need the obs-zoom-to-mouse.lua script from the remote branch here: 
[obs-zoom-to-mouse.lua](https://github.com/BlankSourceCode/obs-zoom-to-mouse/tree/remote)

Follow the instructions in the first repo, to make sure you put the `ljsocket.lua` file next to the OBS script, you should then see a new option to enable the socket server in the script. Running the other program and passing in the hostname will forward the mouse position to the script.

Good luck!

**Comment by JoqniX** [comment]
okie thank you! imma try testing it out now! thanks again for working on this! it really means alot <3

**Comment by JoqniX** [comment]
it works so well! im so thankful! thank you <3

**Comment by JoqniX** [comment]
so nowadays it just becomes too zommed like when i reported the bug! but switching scene fixes it! so yee ig it is fine if this happens? but yee. 

also could you lmk which one i should be downloading  from nowonwards since i'll be using it with remote? 
should i go with the test build or the main one from here? 

# LOG
[obs-zoom-to-mouse.lua] looking...
[obs-zoom-to-mouse.lua] {
  service = 12345,
  addrinfo = cdata<struct addrinfo *>: 0x022ad19273b0,
  family = inet,
  get_port = function: 0x022a8ab3c5a8,
  protocol = tcp,
  get_ip = function: 0x022a8ab3c528,
  socket_type = stream,
  flags = {
  },
}
[obs-zoom-to-mouse.lua] 48.57.0.0
[obs-zoom-to-mouse.lua] OBS Version: 30.0.2
[obs-zoom-to-mouse.lua] Platform: Windows
[obs-zoom-to-mouse.lua] Current settings:
[obs-zoom-to-mouse.lua] {
[obs-zoom-to-mouse.lua]   socket_poll = 10,
[obs-zoom-to-mouse.lua]   debug_logs = true,
[obs-zoom-to-mouse.lua]   use_follow_auto_lock = false,
[obs-zoom-to-mouse.lua]   zoom_value = 2,
[obs-zoom-to-mouse.lua]   zoom_speed = 0.06,
[obs-zoom-to-mouse.lua]   monitor_override_x = 0,
[obs-zoom-to-mouse.lua]   monitor_override_y = 0,
[obs-zoom-to-mouse.lua]   monitor_override_w = 1920,
[obs-zoom-to-mouse.lua]   use_auto_follow_mouse = true,
[obs-zoom-to-mouse.lua]   use_follow_outside_bounds = false,
[obs-zoom-to-mouse.lua]   use_monitor_override = false,
[obs-zoom-to-mouse.lua]   follow_speed = 0.25,
[obs-zoom-to-mouse.lua]   follow_border = 8,
[obs-zoom-to-mouse.lua]   follow_safezone_sensitivity = 4,
[obs-zoom-to-mouse.lua]   monitor_override_h = 1080,
[obs-zoom-to-mouse.lua]   monitor_override_sx = 1,
[obs-zoom-to-mouse.lua]   monitor_override_sy = 1,
[obs-zoom-to-mouse.lua]   monitor_override_dw = 1920,
[obs-zoom-to-mouse.lua]   monitor_override_dh = 1080,
[obs-zoom-to-mouse.lua]   use_socket = true,
[obs-zoom-to-mouse.lua]   socket_port = 12345,
[obs-zoom-to-mouse.lua] }
[obs-zoom-to-mouse.lua] Transition started
[obs-zoom-to-mouse.lua] Zoom crop filter removed
[obs-zoom-to-mouse.lua] Transform info reset back to original
[obs-zoom-to-mouse.lua] Transform crop reset back to original
[obs-zoom-to-mouse.lua] OBS Scene changed
[obs-zoom-to-mouse.lua] Finding sceneitem for Zoom Source '「 VDC 」  -  JOQIE PC'
[obs-zoom-to-mouse.lua] Looking in scene '「 🎥 」  -  Capture'
[obs-zoom-to-mouse.lua] Found sceneitem '「 VDC 」  -  JOQIE PC'
[obs-zoom-to-mouse.lua] WARNING: Could not auto calculate zoom source position and size.
[obs-zoom-to-mouse.lua]          Try using the 'Set manual source position' option and adding override values
[obs-zoom-to-mouse.lua] ERROR: Selected Zoom Source is not a display capture source.
[obs-zoom-to-mouse.lua]        You MUST enable 'Set manual source position' and set the correct override values for size and position.
[obs-zoom-to-mouse.lua] Using source size: 1920, 1080
[obs-zoom-to-mouse.lua] Transition started
[obs-zoom-to-mouse.lua] Zoom crop filter removed
[obs-zoom-to-mouse.lua] Transform info reset back to original
[obs-zoom-to-mouse.lua] Transform crop reset back to original
[obs-zoom-to-mouse.lua] Transition started
[obs-zoom-to-mouse.lua] OBS Scene changed
[obs-zoom-to-mouse.lua] Finding sceneitem for Zoom Source '「 VDC 」  -  JOQIE PC'
[obs-zoom-to-mouse.lua] Looking in scene 'Game'
[obs-zoom-to-mouse.lua] Looking in scene '「 🎥 」  -  Capture'
[obs-zoom-to-mouse.lua] Found sceneitem '「 VDC 」  -  JOQIE PC'
[obs-zoom-to-mouse.lua] WARNING: Could not auto calculate zoom source position and size.
[obs-zoom-to-mouse.lua]          Try using the 'Set manual source position' option and adding override values
[obs-zoom-to-mouse.lua] ERROR: Selected Zoom Source is not a display capture source.
[obs-zoom-to-mouse.lua]        You MUST enable 'Set manual source position' and set the correct override values for size and position.
[obs-zoom-to-mouse.lua] Using source size: 1920, 1080

**Comment by JoqniX** [comment]
ah i accidently opened it. il send the small bug i noticed to the issue i referenced before sorry bout this!
