### ISSUE TITLE
Issue when mask filter is applied

### ISSUE THREAD

**Issue by anasak-dev** [BlankSourceCode/obs-zoom-to-mouse#26]
Thanks for this amazing script, I am using it and it works well but issue is coming when mask filter is applied on screen capture.

Issue is when the screen zooms in, it crops out the mask from some corners and sometime from all corners, if there
is any resolution for it pls let me know, adding some screenshots belo

**Mask applied (normal)**
<img width="1440" alt="mask-applied-normal" src="https://github.com/BlankSourceCode/obs-zoom-to-mouse/assets/14008858/9bcfdce2-ad2f-4bb2-935f-72c884dd76b0">

**Mask when OBS Zoom is enabled**
<img width="1440" alt="mask-changed-after-zoom" src="https://github.com/BlankSourceCode/obs-zoom-to-mouse/assets/14008858/44c94199-fbb3-4f9e-bfb5-2a24f94701d4">

**OBS zoom to mouse filter properties**
<img width="929" alt="obs-zoom-filter-properties" src="https://github.com/BlankSourceCode/obs-zoom-to-mouse/assets/14008858/7a7ab21b-58eb-4c30-90a9-18cfe1600bfb">

**The mask I am using for rounded corners**
![browser-mask](https://github.com/BlankSourceCode/obs-zoom-to-mouse/assets/14008858/3d5b434f-0aa0-4f25-8b58-8a9f5555a91a)

**Comment by BlankSourceCode** [comment]
@anasak-dev This is due to the script forcing the crop filter that it uses for zoom to always be at the bottom of the list so that it zooms in after the mask has already been rendered.

Since you aren't using any other filters, you could probably change the code to make it put the crop filter first, so that the mask renders on top of the zoom, giving you rounded corners after you've zoomed in.

To do that, change [line 733](https://github.com/BlankSourceCode/obs-zoom-to-mouse/blob/c891420a9ae3efef79f455aa9bc77b7a4d94ee8b/obs-zoom-to-mouse.lua#L733)
from:
```
obs.obs_source_filter_set_order(source, crop_filter, obs.OBS_ORDER_MOVE_BOTTOM)
```
to:
```
obs.obs_source_filter_set_order(source, crop_filter, obs.OBS_ORDER_MOVE_TOP)
```

Then just save and reload the script in OBS.

That should let you keep the rounded corners. If you add more filters later it may mess up the zooming especially if you add a custom crop/pad filter, so just something to keep in mind.

Good luck, and thanks for using the script.

**Comment by anasak-dev** [comment]
@BlankSourceCode thanks for your message and the code update.

Unfortunately after updating the said line of code, the issue remains same.
If you need any more details from my end pls lmk, thanks again!

**Comment by anasak-dev** [comment]
@BlankSourceCode pls disregard my last comment, I must be using wrong version of script,
upon updating to the script you mentioned and then updating the line of code did the trick I think, many thanks.
