### ISSUE TITLE
Doesnt Zoom when its in a Scene

### ISSUE THREAD

**Issue by Mackielelz** [BlankSourceCode/obs-zoom-to-mouse#4]
If i have the Source (Monitor) into a Scene (Monitor+Game Scene), and i put this Scene into another (GameScene)
It doesnt zoom..

**Comment by Mackielelz** [comment]
And Thank you for this Script! <3

**Comment by BlankSourceCode** [comment]
I didn't even know nested scenes were a thing you could do in OBS.

I've checked in a fix for this, give it a try and let me know if it is still broken somehow.

Thanks for trying the script!

**Comment by BlankSourceCode** [comment]
@Mackielelz If you still hit the issue with the latest version of the script, let me know. I tested it locally with a Scene nested inside another one, but I'm not sure if that was actually the same setup that you were using. Thanks!

**Comment by tacheconfuse** [comment]
hi @BlankSourceCode i noticed the issue is still happening when the source i want to zoom on is in a **Group**, there's no error in the logs, but it seems like outside of a group, the temp filter is created, but in a group no filter is created.

Thanks for flagging this @Mackielelz, helped me figure out a workaround :)
